### ISSUE TITLE
Binary FBXs' blend shape normal offsets are all zeros

### ISSUE THREAD

**Issue by TJYSunset** [ufbx/ufbx#103]
<details>

<summary>Minimum (?) reproduction example</summary>

The ASCII FBX's normals seem suspicious, but this should demonstrate the point.

### Environment

+ UFBX master @ 6dd7771
+ CMake -> MSVC 17.0 amd64
+ Windows 11

### Input

[Reproduction.zip](https://github.com/ufbx/ufbx/files/14472984/Reproduction.zip)
+ `why.fbx` generated by Blender 4.0: a basic cube with a shape key rotating it by 45°.
+ `why.ascii.fbx` generated by the release binary of [BobbyAnguelov/FbxFormatConverter](https://github.com/BobbyAnguelov/FbxFormatConverter), supposedly using Autodesk SDK, from `why.fbx`.

### Code

```c++
#include <iostream>

#include <ufbx.h>

int main()
{
    auto options = ufbx_load_opts{.ignore_embedded = true,
        .strict = true,
        .generate_missing_normals = true,
        .target_axes = ufbx_axes_right_handed_z_up,
        .target_unit_meters = 1,
        .normalize_normals = true,
        .normalize_tangents = true};
    auto error = ufbx_error();

    {
        auto scene = ufbx_load_file("why.fbx", &options, &error);
        auto shape = scene->meshes[0]->blend_deformers[0]->channels[0]->keyframes[0].shape;
        auto normalOffsets = shape->normal_offsets;
        for (auto i = 0; i < shape->num_offsets; i++)
        {
            std::cout << normalOffsets[i].x << " " << normalOffsets[i].y << " " << normalOffsets[i].z << std::endl;
        }
        ufbx_free_scene(scene);
    }

    std::cout << "===" << std::endl;

    {
        auto scene = ufbx_load_file("why.ascii.fbx", &options, &error);
        auto shape = scene->meshes[0]->blend_deformers[0]->channels[0]->keyframes[0].shape;
        auto normalOffsets = shape->normal_offsets;
        for (auto i = 0; i < shape->num_offsets; i++)
        {
            std::cout << normalOffsets[i].x << " " << normalOffsets[i].y << " " << normalOffsets[i].z << std::endl;
        }
        ufbx_free_scene(scene);
    }
    
    return 0;
}
```

### Output

```
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
===
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 -0.292893 0.707107
0 -0.292893 0.707107
```

</details>

I'm switching from [assimp](https://github.com/assimp/assimp) because their FBX support is quite funky, but assimp can output seemingly normal blend shape normals.

I don't really understand C/C++, but from my investigation, ufbx's and assimp's higher level logic on blend shapes looks exactly the same, so maybe there's something off with the binary parser?

**Comment by bqqbarbhg** [comment]
Thanks for the very detailed report!

It looks like ufbx is loading the blend shape normals exactly as they're defined in the files. I have a [tool](https://github.com/ufbx/ufbx/blob/master/misc/transmute_fbx.py) for converting binary FBX files to ASCII without changing their semantics (well, the files won't be quite valid FBX due to some binary/ASCII differences, but it's useful for debugging).

Using that on `why.fbx` results in the following:

```
Geometry: 857494602, "ShapeKey1\x00\x01Geometry", "Shape" {
    Properties70:
    Version: 100
    Indexes: * 8 { 0, 1, 2, 3, 4, 5, 6, 7 }
    Vertices: * 24 { 0.0, 1.0, -0.41421353816986084, 0.0, -0.41421353816986084, -1.0, 0.0, 0.41421353816986084, 1.0, 0.0, -1.0, 0.41421353816986084, 0.0, 1.0, -0.41421353816986084, 0.0, -0.41421353816986084, -1.0, 0.0, 0.41421353816986084, 1.0, 0.0, -1.0, 0.41421353816986084 }
    Normals: * 24 { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }
}
```

So in that way ufbx seems to be doing the right thing. These zero blend shape normals have confused me on multiple occasions as well, either it's a bug in the exporter or then they're relative to some automatically generated normals? Though I don't see why the ASCII conversion would change them in that case. Also not sure what assimp is doing there, maybe it has some condition for generating normals from the vertices, as it does not seem like there is any valid normal information in the file.

I'll need to look into this a bit more when I have more time, it doesn't really look like a bug per se, but I think the ufbx interface could be improved if the FBX blend shape normals are indeed relative to some normals derived from the positions.

**Comment by TJYSunset** [comment]
> but assimp can output seemingly normal blend shape normals

That was false, sorry about the hasty conclusion. It was obviously only floating point errors in assimp's C# binding (how did that happen is beyond me); the average delta length is 1.2617932E-07. I have just set up an actual C++ project, and assimp outputted all zeroes too.

The third party FBX converter's ASCII normals seem off after more testing (judging by numbers for simple geometries, because I don't have a working renderer right now in the middle of this mess). Maybe that's just more bugs instead of Autodesk SDK's actual behavior.

---

Looks like the only practical solution is to have the exporter write face smoothing flags, then generate new normals by myself. Closing this as this is obviously out of scope for this project. Sorry again for the disruption.

**Comment by bqqbarbhg** [comment]
No worries!

> Closing this as this is obviously out of scope for this project.

Actually I don't think it's necessarily out of scope. I already have a bunch of support for generating normals (respecting edge/face hardness flags), so it would be reasonable to do. Also, this is not the first time this issue surfaces somewhere (it is the first time in the issue tracker, though, so this is not a duplicate issue :D) so adding support for it might actually be worth it.

I added a tracking issue #104 but I'll need to let it simmer for a bit and even then I probably won't have time to work on it for a good while.
