### ISSUE TITLE
Sign of tangents

### ISSUE THREAD

**Issue by Duttenheim** [ufbx/ufbx#105]
Hello!

I just finished integrating UFBX to our content pipeline in our engine (https://github.com/gscept/nebula/pull/209/files) and just remembered that in the FBX SDK you could get the tangent sign by reading the W component, but in UFBX tangents are only vec3. 

I could be wrong about the FBX SDK, I just made that assumption and it seemed correct, but was wondering if there is some other way of getting the tangent sign?

Thanks,
Gustav

**Comment by bqqbarbhg** [comment]
Heya!

This is actually an issue I've been aware for a long time but I try to avoid exposing features I don't fully understand, and I generally want to simplify the FBX format for users where possible (I know I certainly would be confused why my normals are 4-dimensional).

Currently they are accessible by using `ufbx_load_opts.retain_dom` and parsing them manually from `NormalsW` / `TangentsW` / `BinormalsW` but I wouldn't recommend it.

I think the simplest way to expose them would be to add mesh attributes and let users interpret them:
```c
ufbx_vertex_real vertex_normal_w;
ufbx_vertex_real vertex_tangent_w;
ufbx_vertex_real vertex_bitangent_w;
```

Do you have an use case, or have you seen a file that utilizes these components for something? I really prefer to have real-world test cases before starting to implement features, so I can make sure ufbx behaves correctly for actual data, instead of just hypothetical synthetic test cases. (no sweat for contributing test cases, just the general idea how to reproduce those files should suffice for me to make some test data)

**Comment by Duttenheim** [comment]
Hello! 

The reason why I was looking for this is because in our engine, we infer the bitangent in the shader to reduce vertex size for throughout reasons. I guess it's not super important to store the sign in ufbx, but it would be super convenient if there was a method for calculating it. I have no idea if the FBX SDK tangent W is actually reliable as the sign 😆. 

I could provide an FBX where the tangent W component actually differs between polygons if you'd like to take a look, but it would take a little bit of time to find one if you don't mind. 

I also want to applaud you for the work you've done here. It took just a hours here and there to convert from the FBX SDK to ufbx and have it work just as expected.

Thanks,
Gustav

**Comment by bqqbarbhg** [comment]
> The reason why I was looking for this is because in our engine, we infer the bitangent in the shader to reduce vertex size for throughout reasons.

I think this usually can be done by storing the sign difference of the bitangent and calculated bitangent ie:
```c
Bitangent_Sign = sign(dot(cross(Normal, Tangent), Bitangent))
```
and thus shouldn't need the tangent sign information from FBX, which is why I'm a bit confused what the values mean (especially as there's a W component for normal/tangent/bitangent). It probably has something to do with handedness and winding but I'd need to experiment with it.

> I have no idea if the FBX SDK tangent W is actually reliable as the sign 😆.

In general after seeing so many FBX files I've come to assume that nothing is reliable :D

> I could provide an FBX where the tangent W component actually differs between polygons if you'd like to take a look, but it would take a little bit of time to find one if you don't mind.

That would be really helpful! The only files I've seen have W=1 for all components or W=0 (!) from some 3ds Max exports, which is weird as you'd think the W component is either 1 or -1.. If it's non public you can for example DM me in [Twitter](https://twitter.com/bqqbarbhg) or mail to `bqqbarbhg` gmail.

> I also want to applaud you for the work you've done here. It took just a hours here and there to convert from the FBX SDK to ufbx and have it work just as expected.

Thanks a lot! Your implementation is actually the first time I've seen someone replace the FBX SDK with ufbx, I was surprised how little difference was required there even though ufbx was definitely not designed with that in mind originally.

Definitely feel free to leave further issues if there's something that doesn't work right compared to the SDK or if there's something missing!

**Comment by Duttenheim** [comment]
With calculating the sign, is there a guarantee there are even bitangents in the FBX? And if there aren't any, is there an API to have ufbx calculate missing tangent space data? I have no idea what requirements the FBX format imposes, but isn't it technically possible to have normals and tangents but no bitangents? I do remember some FBX's having only normals, but we have code to generate tangent space vectors if they are missing

Perhaps this is another one of those examples where an example would be good to gauge the validity of the edge case 😄. 

Thanks,
Gustav

**Comment by bqqbarbhg** [comment]
I don't think there's any guarantees, not sure if I have seen any files having only `Tangent` but not `Binormal` (sic, bitangent) vertex attributes. I have been considering adding generation but currently I assume most people would want the tangents to be equivalent to what `mikktspace` generates, and adding that feels like a bit much, especially given that I feel like ufbx has been accumulating a bit much "unnecessary" features.

FBX files having only normals is relatively common, I think quite a few exporters have an "export tangent space" option and of course if there's meshes with no UVs there's no tangent space either. ufbx can internally certainly handle meshes with tangents without bitangents, as I have pretty exhaustive fuzzing setup that has surely generated files with all permutations of missing attributes.

**Comment by perkele1989** [comment]
Storing precalculated bitangent sign is a method used to produce correct results by maintaining the same tangent space throughout a pipeline. Normalmapping is its own science, and not something I'm going to get into much details for here. 

In my workflow, I export FBX's from Blender, which includes tangentspace calculated via mikktspace (industry standard). Keeping the sign is important, and its applied in shader for us too, as in Duttenheims case (though I suspect in his case the real reason its applied in shader like this is not to save data or bandwidth, but because mikktspace requires it to get correct results).

I would vouch for adding like this:

```c
	ufbx_vertex_vec3 vertex_position; 
	ufbx_vertex_vec3 vertex_normal; 
	ufbx_vertex_vec2 vertex_uv;
	ufbx_vertex_vec3 vertex_tangent;
	ufbx_vertex_vec3 vertex_bitangent;
	ufbx_vertex_real vertex_bitangent_sign; // <-- optional as the others
	ufbx_vertex_vec4 vertex_color; 
	ufbx_vertex_real vertex_crease;
```

that way, it could optionally be used if its available, and ufbx would support a massive amounts of workflows properly in the process. I think many people don't have the full picture of tangentspace and how mikktspace works in practice in softwares like Blender and Unreal Engine, but it's pretty much required if you want to do things right, and get proper normal mapping with correct results.

Now, how to get it from the FBX file is something I'll leave to you, but I know its often stored in bitangent.w where sourcedata has 4-comp vectors

Best,

**Comment by bqqbarbhg** [comment]
Yeah, maintaining consistent tangent space is vital for normal mapping and mikktspace is the standard way to do it (which is why I didn't want to implement my own, slightly different, tangent space generation in ufbx).

However, recovering the bitangent sign should be always doable if you are provided with tangent and bitangent, as mikktspace defines the bitangent as `vB = sign * cross(vN, vT);`. Thus, you can recover the sign from `sign(dot(cross(vN, vT), vB))` as I mentioned above.

I ran some experiments in b71a056, and interestingly it seems that exporters store the sign in `TangentsW`. Still not sure what `NormalsW` and `BinormalsW` represent though. Here's a rundown of the results:

* Blender 3.4 (FBX 7400): No W component
* Maya FBX 6100: No W component
* Maya FBX 7700: `NormalsW=1, TangentsW=sign, BinormalsW=1`
* 3ds Max FBX 6100: No W component
* 3ds Max FBX 7700: `NormalsW=0, TangentsW=sign, BinormalsW=1`

Need to look into this a bit further, but it does seem like if `TangentsW` is present it will contain the bitangent sign. Not sure why it is encoded separately due to the recoverability I mentioned earlier.

Not quite sure what the right call for API in ufbx is. If the tangent sign is exposed it would be confusing as it's missing half the time depending on the exporter. One possibility would be to add `ufbx_bitangent_sign(vec3 normal, vec3 tangent, vec3 bitangent)` that users can call to calculate the correct sign, regardless of whether the exporter wrote `TangentsW` or not. I'll probably still want to expose the `W` components in case (especially if I can figure out what's going on with `NormalsW`) but it should be very clear from the API that it may be missing etc.

**Comment by perkele1989** [comment]
Ah, I apologize for not reading the thread more thoroughly. Thank you for a quick response, and thank you for a seemingly great library!

**Comment by bqqbarbhg** [comment]
@perkele1989 No worries! I ended up finding those test cases and a probable meaning for `TangentsW` because of it, so I count it as a win :D

**Comment by bqqbarbhg** [comment]
Plot twist: I created a very simple test case mesh with two faces, one with mirrored UV and one without ([file in repo here](https://github.com/ufbx/ufbx/blob/bc2a14b88c1ee60ed953782cd28f4035b64b1665/data/maya_tangent_sign_mixed_7700_ascii.fbx)):

![image](https://github.com/ufbx/ufbx/assets/3875461/bd084ee6-95b2-41e4-9a52-9f287183556e)

The binormals and tangents are mapped as non-indexed `ByPolygonVertex` so they have contiguous values for the indices, ie. first face is indices `[0,3]` and second one is `[4,7]`:

```
LayerElementBinormal: 0 {
	Version: 102
	Name: "map1"
	MappingInformationType: "ByPolygonVertex"
	ReferenceInformationType: "Direct"
	Binormals: *24 {
		a: 0,-0,-1,-0,0,-1,-0,0,-1,-0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1
	} 
	BinormalsW: *8 {
		a: 1,1,1,1,1,1,1,1
	} 

}
LayerElementTangent: 0 {
	Version: 102
	Name: "map1"
	MappingInformationType: "ByPolygonVertex"
	ReferenceInformationType: "Direct"
	Tangents: *24 {
		a: -1,0,-0,-1,0,0,-1,0,0,-1,0,0,1,-0,0,1,0,0,1,0,0,1,0,0
	} 
	TangentsW: *8 {
		a: -1,-1,1,-1,-1,-1,1,1
	} 
}
```

Ignoring the signs of the zero all binormals (sic, bitangents) are `(0,0,-1)` which is correct. Formatting the tangents a bit more cleanly results in:

```
Tangents: *24 {
	-1,0,-0,
	-1,0,0,
	-1,0,0,
	-1,0,0,
	1,-0,0,
	1,0,0,
	1,0,0,
	1,0,0
} 
```

Again, ignoring the signed zero business this makes sense as the first face is flipped in the X axis. Thus, if `TangentsW` would actually correspond to the sign of the bitangent we would expect something like:

```
TangentsW: *8 {
	a: -1,-1,-1,-1,1,1,1,1
} 
```

However, what is actually stored in the file makes no sense: it contains 5 times `-1` and 3 times `1`?! If we overlap `Tangents` and `TangentsW` we get:

```
TangentsWithW: {
	-1,0,0, -1,
	-1,0,0, -1,
	-1,0,0, 1,
	-1,0,0, -1,
	1 ,0,0, -1,
	1 ,0,0, -1,
	1 ,0,0, 1,
	1 ,0,0, 1,
} 
```

There's no pattern here that I could tell, so I'm again thrown off what `TangentsW` could mean here.

@Duttenheim let me know if you had some cases where you found `TangentsW` meaningful or happen to see if I'm missing something here?

**Comment by bqqbarbhg** [comment]
Reading the W component of normals/tangents/bitangents works as of [v0.12.0](https://github.com/ufbx/ufbx/releases/tag/v0.12.0).

Use `ufbx_load_opts.retain_vertex_attrib_w = true` to retain them in the scene. After that every vertex attribute has a parallel array to values named `values_w`, for example `ufbx_mesh.vertex_tangent.values_w[]`. There also is an accessor `ufbx_get_vertex_w_vec3()` which mirrors the usage of `ufbx_get_vertex_vec3()`, just returning the W component.

That said, I still wouldn't recommend relying on it as from what I've seen it has quite a bunch of issues.
