### ISSUE TITLE
Euler_rotation for each node is 0,0,0 when it definitely should not be 

### ISSUE THREAD

**Issue by temper-studios** [ufbx/ufbx#62]
Not 100% sure this is a bug, but for a particular file, euler rotations are all zero even when they should have non zero rotations.
Unfortunately I can't upload the file here as it is too big.

**Comment by bqqbarbhg** [comment]
Sounds very interesting, unfortunately I can't do much without the file, I guess you could upload it to any file sharing website and for example DM me the link in Twitter [@bqqbarbhg](https://twitter.com/bqqbarbhg) if you don't want to link it here publicly.

For some initial speculation, program was the .fbx file made in?

**Comment by temper-studios** [comment]
Tried DMing you on twitter but didn't work? Not sure if it's something to do with new twitter policy or something?

**Comment by bqqbarbhg** [comment]
Finally had a chance to look at this, sorry for the delay. I added the file to my non-public test cases and it seems to match the output exported from Maya. Took a look at the file and it turns out Mixamo does something extremely cursed here. ufbx is doing the right thing by reporting `euler_rotation={0,0,0}` as if you look into the `ufbx_props` of the nodes you can see that `"Lcl Rotation"` is indeed `{0,0,0}`...

Turns out Mixamo uses `"PreRotation"` to store some sort of bind pose angles, for example in the node `"mixamorig:LeftUpLeg"` we have properties:

```c
{ name="Lcl Rotation", value_vec3={ x=0.0, y=0.0, z=0.0 } }
{ name="PreRotation", value_vec3={ x=-1.8426644057317612, y=0.11972419242468679, z=-176.28380396587519 } }
```

If you want the fully transformed rotation for some reason you can convert it via
```c
ufbx_vec3 rotation_euler = ufbx_quat_to_euler(node->local_transform.rotation, UFBX_ROTATION_ORDER_XYZ);
```

**Comment by temper-studios** [comment]
Cheers for looking into it.

 I thought I was going mad. Glad someone verified I'm not xD

Mixamo does seem cursed. But now can move on. Thanks
