### ISSUE TITLE
Support multiple methods for handedness conversion?

### ISSUE THREAD

**Issue by speakfool** [ufbx/ufbx#89]
Hi,

I'm currently testing ufbx in handedness. I saw a related branch here, but no details about how handedness is handled here. 
My use case is to convert right handed model into left handed.

I added
`opts.target_axes = ufbx_axes_left_handed_y_up;`
creates a -1 scale on root node,  and if I set
`opts.space_conversion = UFBX_SPACE_CONVERSION_ADJUST_TRANSFORMS`
 in
`static void ufbxi_update_adjust_transforms(ufbxi_context *uc, ufbx_scene *scene)`
this line
`ufbx_real root_scale = ufbxi_min3(root_transform.scale);`
also creates a negative scale.

Is there any documentation about how this is affected? 
Are the skinned mesh vertices or animations affected by the space conversion options? 

Thanks!

**Comment by bqqbarbhg** [comment]
Heya!

Great timing on the issue, I've just been working on this :D Currently handedness conversion is pretty terrible as you've seen, it can at most flip the root scale which is not great.

I'm working on a PR #85 which is pretty stable already, which supports proper handedness conversion that modifies the geometry, so I'd recommend checking that branch out! (also I'd really appreciate feedback if you end up using it, as I'm still working on it).

You can enable it like this:

```c
ufbx_load_opts opts = { 0 };
opts.space_conversion = UFBX_SPACE_CONVERSION_ADJUST_TRANSFORMS;
// .. or new and swanky UFBX_SPACE_CONVERSION_MODIFY_GEOMETRY from the same PR
opts.target_axes = ufbx_axes_left_handed_y_up;
opts.handedness_conversion_axis = UFBX_MIRROR_AXIS_Z; // or X,Y..
```

Currently it will also by default reverse winding for all faces when doing handedness conversion, but I'm not sure if that is ideal default behavior, you can disable that behavior via:

```c
opts.handedness_conversion_retain_winding = true;
```

Documentation is still on the way but by default all conversions are done in a way that the scene stays intact, but most conversions do not touch geometry or animation curves directly, but rather modify an "adjust" transform on nodes that ufbx evalautes internally. This is only a concern if you plan to manually evaluate the transforms, which I wouldn't recommend.

Feel free to ask if there's something unclear and sorry about the state of the documentation!

**Comment by speakfool** [comment]
Hi!
Great to know it's done here! 

UFBX_SPACE_CONVERSION_MODIFY_GEOMETRY seems to be my desired behaviour.
And for mirror and winding flip, I guess only one is needed for converting handedness.

I just tried the handedness-conversion branch with this configuration.
`
        opts.target_axes = ufbx_axes_left_handed_y_up;
        opts.target_unit_meters = 1.0f;
        opts.space_conversion = UFBX_SPACE_CONVERSION_MODIFY_GEOMETRY;
        opts.handedness_conversion_axis = UFBX_MIRROR_AXIS_X;
        opts.handedness_conversion_retain_winding = true;
`

The skin vertices works all fine in my test case.
But it seems that mirror didn't change node's local transform, which i used to construct the refpose.
The result is the debug drawed skeleton is mirrored with the skin rendered.

Should I manually multiply by values like 'adjust_pre_rotation' ?

Thanks

**Comment by bqqbarbhg** [comment]
All the `adjust_*` transforms are handled internally by ufbx, you only need them if you're interpreting the transform yourself from `ufbx_prop`s. If you're using `ufbx_node.local_transform` it should just work. There's a possibility that something is still broken, if you have a file you can share I can take a look (though no pressure if not).

**Comment by speakfool** [comment]
Thanks for the clarification.I'll check with the artist if I can share the model next monday. 
But I think I found something might be useful.

If I change UFBX_MIRROR_AXIS_X to UFBX_MIRROR_AXIS_Z, it works fine for the previously broken asset( "Asset A").
Another asset("Aseset B") which was correct with mirrox,  goes upside down. But both assets skeleton are consistent with skin.

Asset A has `original_axis_up == UFBX_COORDINATE_AXIS_POSITIVE_Z (4)`
Asset B is UFBX_COORDINATE_AXIS_UNKNOWN. 

Is the mirror setting something we can infer from target_axes parameter?

**Comment by bqqbarbhg** [comment]
Very interesting, the mirroring setting should not matter for the visual result of the mesh, as the scene is also rotated to compensate for it. In practice the only difference between `UFBX_MIRROR_AXIS_X/Y/Z` is what axis the geometry is mirrored by, for example all my tests (for example [maya_axes_lefthanded_modify](https://github.com/ufbx/ufbx/blob/2070f2d2cf08c066defd5b9fdeea5bba0339bdec/test/test_transform.h?ts=4#L1143-L1161)) test all the mirror axes for the same scene, diffing the result to a reference .obj, so it's very strange if it actually changes behavior.

Are you doing anything else than `ufbx_load_*()` and inspecting the scene, via ufbx helpers like `ufbx_node.local_transform` etc?

**Comment by speakfool** [comment]
Yes, I construct the refpose using scene->bones[bi]->instances[0].local_transform.
Instead of using `geometry_to_bone` as in viewer.c example, I use `loca_transform` as refpose.
Then I inverse the refpose, and use it in my skinning shader.
So in my render case, all bone transforms uniforms are identity.

FYI: By dumping the bone local transform, 
I found every bone transform is mirrored some how like:
mirror_x : transform:quat:[-0.500, -0.500, -0.500, 0.500], t:[0.000,0.988,-0.037],s:[1.000]
mirror_z:  transform:quat:[0.500, 0.500, -0.500, 0.500], t:[0.000,0.988,-0.037],s:[1.000]

**Comment by bqqbarbhg** [comment]
Yeah mirroring the transforms is correct, though strangely the translation does not look mirrored in the Z axis there for `mirror_z` which should happen, or are those world-space transforms (though then the rotation should be identical I think). Are you taking the world pose of the mesh into account when making the custom bind matrices?

You'd want something like `inverse(bone_node->node_to_world) * mesh_node->node_to_world` for the skinning matrix to account for the mesh transformation right? (multiplication order might be inverted for left-handed or row-major matrices, not sure how those work out).

**Comment by speakfool** [comment]
Looking at more bone data, mirrored in the Z axis is done for non-root node.
mirrox:

bone name:Bip001, transform:quat:[-0.500, -0.500, -0.500, 0.500], t:[0.000,0.988,-0.037],s:[1.000]
bone name:Bip001 Pelvis, transform:quat:[-0.500, 0.500, 0.500, 0.500], t:[-0.000,0.000,0.000],s:[1.000]
bone name:Bip001 Spine, transform:quat:[-0.000, 0.000, -0.050, 0.999], t:[-0.099,0.028,0.000],s:[1.000]
bone name:Bip001 Spine1, transform:quat:[-0.000, -0.000, 0.068, 0.998], t:[-0.060,-0.000,-0.000],s:[1.000]
bone name:Bip001 Spine2, transform:quat:[0.000, -0.000, 0.125, 0.992], t:[-0.102,-0.000,-0.000],s:[1.000]
bone name:Bip001 Neck, transform:quat:[-0.000, 0.000, -0.190, 0.982], t:[-0.185,0.004,0.000],s:[1.000]
bone name:Bip001 Head, transform:quat:[0.000, -0.000, 0.048, 0.999], t:[-0.074,-0.000,0.000],s:[1.000]
bone name:+EyeBone L A01, transform:quat:[-0.699, 0.699, 0.104, 0.104], t:[-0.062,0.035,0.026],s:[1.000]
bone name:+EyeBone R A01, transform:quat:[-0.700, 0.700, -0.103, -0.102], t:[-0.062,0.035,-0.026],s:[1.000]
bone name:+ToothBone D A01, transform:quat:[0.683, -0.730, -0.000, -0.000], t:[-0.001,0.088,0.000],s:[1.000]
bone name:+ToothBone U A01, transform:quat:[-0.681, 0.733, 0.000, 0.000], t:[-0.007,0.088,0.000],s:[1.000]
bone name:+HairS L F01, transform:quat:[0.166, -0.983, -0.075, -0.033], t:[-0.041,-0.022,0.070],s:[1.000]

mirrorz:
bone name:Bip001, transform:quat:[0.500, 0.500, -0.500, 0.500], t:[0.000,0.988,-0.037],s:[1.000]
bone name:Bip001 Pelvis, transform:quat:[0.500, 0.500, -0.500, 0.500], t:[0.000,0.000,-0.000],s:[1.000]
bone name:Bip001 Spine, transform:quat:[0.000, 0.000, 0.050, 0.999], t:[0.099,0.028,-0.000],s:[1.000]
bone name:Bip001 Spine1, transform:quat:[0.000, -0.000, -0.068, 0.998], t:[0.060,-0.000,0.000],s:[1.000]
bone name:Bip001 Spine2, transform:quat:[-0.000, -0.000, -0.125, 0.992], t:[0.102,-0.000,0.000],s:[1.000]
bone name:Bip001 Neck, transform:quat:[0.000, 0.000, 0.190, 0.982], t:[0.185,0.004,-0.000],s:[1.000]
bone name:Bip001 Head, transform:quat:[-0.000, -0.000, -0.048, 0.999], t:[0.074,-0.000,-0.000],s:[1.000]
bone name:+EyeBone L A01, transform:quat:[0.699, 0.699, -0.104, 0.104], t:[0.062,0.035,-0.026],s:[1.000]
bone name:+EyeBone R A01, transform:quat:[0.700, 0.700, 0.103, -0.102], t:[0.062,0.035,0.026],s:[1.000]
bone name:+ToothBone D A01, transform:quat:[-0.683, -0.730, 0.000, -0.000], t:[0.001,0.088,-0.000],s:[1.000]
bone name:+ToothBone U A01, transform:quat:[0.681, 0.733, -0.000, 0.000], t:[0.007,0.088,-0.000],s:[1.000]
bone name:+HairS L F01, transform:quat:[-0.166, -0.983, 0.075, -0.033], t:[0.041,-0.022,-0.070],s:[1.000]


As you said, I didn't take mesh node into account.  I'll try it later, and let you know the result.


And I just checked the mesh_node->node_to_world, something strange is that mesh_node->node_to_world is identity, but mesh_node->euler_rotation has 90 degree rotation
<HTML>
<body>



  | Name | Value | Type
-- | -- | -- | --
  | rotation_order | UFBX_ROTATION_ORDER_XYZ (0) | ufbx_rotation_order
▶ | euler_rotation | { x=90.000002504478061 y=-0.0000000000000000 z=0.0000000000000000 } | ufbx_vec3
◢ | node_to_parent | {m00=1.0000000000000000 m10=0.0000000000000000 m20=0.0000000000000000 ...} | ufbx_matrix
  | ◢ cols | 0x00000234247cc430 {{ x=1.0000000000000000 y=0.0000000000000000 z=0.0000000000000000 }, { x=0.0000000000000000 y=0.99999999999999900 z=-4.3711388175715620e-08 }, ...} | ufbx_vec3[4]
  | ▶ [0] | { x=1.0000000000000000 y=0.0000000000000000 z=0.0000000000000000 } | ufbx_vec3
  | ▶ [1] | { x=0.0000000000000000 y=0.99999999999999900 z=-4.3711388175715620e-08 } | ufbx_vec3
  | ▶ [2] | { x=-0.0000000000000000 y=4.3711388175715620e-08 z=0.99999999999999900 } | ufbx_vec3
  | ▶ [3] | { x=0.0000000000000000 y=0.0000000000000000 z=-0.0000000000000000 } | ufbx_vec3
◢ | node_to_world | {m00=1.0000000000000000 m10=0.0000000000000000 m20=0.0000000000000000 ...} | ufbx_matrix
  | ◢ cols | 0x00000234247cc490 {{ x=1.0000000000000000 y=0.0000000000000000 z=0.0000000000000000 }, { x=0.0000000000000000 y=0.99999999999999900 z=-4.3711388175715620e-08 }, ...} | ufbx_vec3[4]
  | ▶ [0] | { x=1.0000000000000000 y=0.0000000000000000 z=0.0000000000000000 } | ufbx_vec3
  | ▶ [1] | { x=0.0000000000000000 y=0.99999999999999900 z=-4.3711388175715620e-08 } | ufbx_vec3
  | ▶ [2] | { x=0.0000000000000000 y=4.3711388175715620e-08 z=0.99999999999999900 } | ufbx_vec3
  | ▶ [3] | { x=0.0000000000000000 y=0.0000000000000000 z=0.0000000000000000 } | ufbx_vec3
  | adjust_mirror_axis | UFBX_MIRROR_AXIS_Z (3) | ufbx_mirror_axis



</body>
</HTML>

**Comment by bqqbarbhg** [comment]
Yeah you may end up with identity transforms even if `euler_rotation` is not `(0,0,0)` as `euler_rotation` represents the value in the FBX file. I should probably get rid of that field anyways as it's not a "true" Euler rotation, since it doesn't include the `PreRotation` and `PostRotation` properties that you'd need to handle to be correct.

The most primitive "correct" value in the nodes is `local_transform`, which has the translation/rotation/scale with all the goofy FBX transform logic and axis conversion applied. All the `x_to_y` matrices are then derived from those transforms.

**Comment by speakfool** [comment]
[TestAsset.zip](https://github.com/ufbx/ufbx/files/12914046/TestAsset.zip)

Hi, I just updated the test files with some parts cleaned. May look like broken but they're not. 
![TestAssets](https://github.com/ufbx/ufbx/assets/1833084/008596e6-f275-4167-8102-ebcedc63bdfa)

**Comment by bqqbarbhg** [comment]
Alright did a deep dive on this, thanks for the test model!

Turns out there were issues on ufbx side, but only when either:

* Using `UFBX_SPACE_CONVERSION_TRANSFORM_ROOT` with handedness _and_ non-identity axis conversion (eg. Z up to Y up)
* `ufbx_skin_cluster.bind_to_world` ignored all unit conversion
* `ufbx_skin_cluster.mesh_node_to_bone` and `ufbx_skin_cluster.geometry_to_bone` was broken under unit/axis/handedness conversion if the file is missing explicit bind matrices, which is extremely uncommon (does not happen in the file linked for example)

I fixed all these I could find in [a5e4c1f](https://github.com/ufbx/ufbx/pull/85/commits/a5e4c1f1ed0129c8e6d841627c0d260c0b9bc9cb), but it seems like none of the conditions should apply to you as you were calculating the bind matrices manually. Also using the ufbx-recommended `ufbx_skin_cluster.geometry_to_bone` did work in practically all cases, as long as the files are not cursed.

Finally, I tried to calculate the bind space manually as you plan to do, I did the following (in the Godot importer as I don't have a good visualizer for bones currently), where I applied the `inverse(bone_node->node_to_world) * mesh_node->node_to_world` computation I mentioned earlier:

```cpp
Transform3D bone_to_world = _as_xform(fbx_cluster->bone_node->node_to_world);
Transform3D mesh_to_world = _as_xform(skin_mesh->instances[0]->node_to_world);
Transform3D world_to_bone = bone_to_world.affine_inverse();
Transform3D mesh_to_bone = world_to_bone * mesh_to_world;

skin->inverse_binds.write[skin_i] = mesh_to_bone;
```

Either doing this or using the ufbx-provided `ufbx_skin_cluster.geometry_to_bone` had correct results for me for any `ufbx_mirror_axis` X/Y/Z option:

![image](https://github.com/ufbx/ufbx/assets/3875461/c2235ac1-79c3-4746-96c5-581d31684368)

Using for example the following options to be exact, the eyes seemed to have geometry transforms, so if you're not handling them manually I recommend `UFBX_GEOMETRY_TRANSFORM_HANDLING_HELPER_NODES` or `UFBX_GEOMETRY_TRANSFORM_HANDLING_MODIFY_GEOMETRY`, though that _should_ apply only to the eyes:

```cpp
ufbx_load_opts opts = {};
opts.target_axes = ufbx_axes_left_handed_y_up;
opts.target_unit_meters = 1.0f;
opts.space_conversion = UFBX_SPACE_CONVERSION_MODIFY_GEOMETRY;
opts.geometry_transform_handling = UFBX_GEOMETRY_TRANSFORM_HANDLING_HELPER_NODES;
opts.handedness_conversion_axis = UFBX_MIRROR_AXIS_Y;
```

By the way, if the matrix names seem weird I'm following [this style](https://www.sebastiansylvan.com/post/matrix_naming_convention/), but not inverting the names for standard multiplication order (so `A_to_C = B_to_C * A_to_B` is correct)

**Comment by speakfool** [comment]
Thank you for your reply and explain! That really narrows down my problem.

I found several mistake I made, the biggest one is that, I only included 'UFBX_ELEMENT_BONE', but actually many node with 'UFBX_ELEMENT_EMPTY' should be included in hierachy, that's why my use of 'local_transform' is not working.

Now I got the skeleton right, but the mesh part is not what I expected.

![image](https://github.com/ufbx/ufbx/assets/1833084/f143c201-7ba3-4eb2-82fa-e43c4f90f006)

I tested using UFBX_GEOMETRY_TRANSFORM_HANDLING_MODIFY_GEOMETRY, and I was expecting some rotation on mesh geometry so that geometry is rotated correctly, but it turns out the 'geometry transform' on the 'Body'  is identity. The rotation is on 'local_transform' of the node.
So I manually bake the node_to_world geometry to mesh geometry to fix it.

![image](https://github.com/ufbx/ufbx/assets/1833084/e7e369c2-316b-417c-9819-583a20729b90)


Here my final questions are:
1.  Is it ok for ufbx to bake geometry like this with some flag? Because in game engine, you certainly don't have mesh transform, and it is usually introduced by handedness or axis conversion. 
2.  Does 'local_transform' or 'node_to_world' include geometry transform?

Thanks!

**Comment by bqqbarbhg** [comment]
In general in FBX you want to inspect the node graph itself, not just bones specifically, and pretty much anything can be under a transformed node hierarchy. I don't think the body itself had geometry transform so that's probably not the issue, I'm assuming the rotation is caused by axis conversion or something else.

(1) I'm probably not going to implement as many engines do want to retain the mesh transforms in the scene graph, like for example Godot which I took the screenshot from. Usually my approach for these things is that I want to provide users an easy way to handle such things, for example you can ignore all transform complexity in any mode by using `ufbx_transform_position(&node->geometry_to_world, vertex);`, and similar helpers like `ufbx_matrix_for_normals()`. Similar reasoning to as why ufbx does not have a "triangulate" flag for loading, as it's really straightforward to do in the mesh processing code.

(2) also depends on settings, geometry transforms are a cursed feature in FBX that lets you transform geometry without affecting children, which is not supported in nearly any scene graph. If you specify `UFBX_GEOMETRY_TRANSFORM_HANDLING_HELPER_NODES`, ufbx will create new nodes between parents and meshes to handle the geometry transforms.

Given that your engine requires meshes to not have transform I'd say that's the correct way to use ufbx, so I'd say the issue is mostly in the lack of documentation, there's some up at https://ufbx.github.io/ but it's not linked yet as it's woefully incomplete. Hopefully some day I'll have time to work on it, I'll make sure to mention transforming meshes to world space now :D

**Comment by speakfool** [comment]
Thank you for help!

Last time I use FBX SDK was about eight years ago and it took me weeks to solve all the pitfalls. 
And that's a close source SDK provided by a big company. ufbx is really easier to use compared with that. 

Geometry transform should be meant for non-inherit transform and pre/post rotation is for modify joint orientation without ruining the local transform animcurve. I can remember something like that,,, really not good for game engines.

I agree the core lib should not do engine specific jobs, but no harm to have some utility function that does common tasks, or many another example usage. Since there is already 'ufbx_triangulate_face' and 'ufbx_generate_indices' :D

FBX SDK provides something like a ConvertScene or ConvertPivot function, which is usually enough for most usage. But you have no control over _how_ the left to right convertion is done.

For documentation, I'm expecting what every transform means and how they compose the final transform you need for skinning a vertex on cpu :D

Again, really cool llibrary!
